Repository jazz-meet/jazz-meet, pull requests merged in 2023-11, with the labels that each got.

#59 공연장 검색 기능 구현
  fe/user/src/components/SearchBar.tsx
  fe/user/src/hooks/useVenueList.ts
  fe/user/src/types/api.types.ts
  fe/user/src/utils/getQueryString.ts
Labels: feat, FE

#73 path alias 개편
  fe/user/src/apis/fetchData.ts
  fe/user/src/apis/show.ts
  fe/user/src/apis/venue.ts
  fe/user/src/constants/COORDINATE.ts
  fe/user/src/hooks/useVenueList.ts
  fe/user/src/layouts/BaseLayout/Header/index.tsx
  fe/user/src/layouts/BaseLayout/index.tsx
  fe/user/src/pages/InquiryPage/Editor/index.tsx
  fe/user/src/pages/InquiryPage/index.tsx
  fe/user/src/pages/MainPage/MainSection/AroundVenus.tsx
  fe/user/src/pages/MainPage/MainSection/CardList/Cards/AroundVenueCard.tsx
  fe/user/src/pages/MainPage/MainSection/CardList/Cards/UpcomingShowCard.tsx
  fe/user/src/pages/MainPage/MainSection/UpcomingShows.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/BasicInfo.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/VenueItem/Description.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/VenueItem/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/index.tsx
  fe/user/src/pages/MapPage/index.tsx
  fe/user/src/router.tsx
  fe/user/src/types/api.types.ts
  fe/user/tsconfig.json
Labels: refactor, FE

#69 fix: 핀 목록 조회 - 검색 word가 null로 들어올 경우 빈 배열 응답하도록 수정
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/VenueController.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueService.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/service/VenueServiceTest.java
Labels: fix, BE

#70 공연장 위치 정보(핀) 목록 조회 - 지도 기반 API 구현
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/VenueController.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/response/VenuePinsResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/mapper/VenueMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/repository/VenueQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueService.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/util/VenueUtil.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/vo/VenuePins.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/controller/VenueControllerTest.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/repository/VenueQueryRepositoryTest.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/service/VenueServiceTest.java
Labels: feat, BE

#75 검색으로 공연장 위치 정보 조회
  fe/user/src/apis/venue.ts
  fe/user/src/constants/MAP.ts
  fe/user/src/hooks/useUserCoordinate.ts
  fe/user/src/hooks/useVenueList.ts
  fe/user/src/pages/MapPage/Map/index.tsx
  fe/user/src/stores/useUserCoordinateStore.ts
  fe/user/src/utils/map.ts
Labels: feat, FE

#76 release로 merge
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/VenueController.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/response/VenuePinsResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/mapper/VenueMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/repository/VenueQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueService.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/util/VenueUtil.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/vo/VenuePins.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/controller/VenueControllerTest.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/repository/VenueQueryRepositoryTest.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/service/VenueServiceTest.java
  fe/user/src/apis/fetchData.ts
  fe/user/src/apis/show.ts
  fe/user/src/apis/venue.ts
  fe/user/src/components/SearchBar.tsx
  fe/user/src/constants/COORDINATE.ts
  fe/user/src/constants/MAP.ts
  fe/user/src/hooks/useUserCoordinate.ts
  fe/user/src/hooks/useVenueList.ts
  fe/user/src/layouts/BaseLayout/Header/index.tsx
  fe/user/src/layouts/BaseLayout/index.tsx
  fe/user/src/pages/InquiryPage/Editor/index.tsx
  fe/user/src/pages/InquiryPage/index.tsx
  fe/user/src/pages/MainPage/MainSection/AroundVenus.tsx
  fe/user/src/pages/MainPage/MainSection/CardList/Cards/AroundVenueCard.tsx
  fe/user/src/pages/MainPage/MainSection/CardList/Cards/UpcomingShowCard.tsx
  fe/user/src/pages/MainPage/MainSection/UpcomingShows.tsx
  fe/user/src/pages/MapPage/Map/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/BasicInfo.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/VenueItem/Description.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/VenueItem/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/index.tsx
  fe/user/src/pages/MapPage/index.tsx
  fe/user/src/router.tsx
  fe/user/src/stores/useUserCoordinateStore.ts
  fe/user/src/types/api.types.ts
  fe/user/src/utils/getQueryString.ts
  fe/user/src/utils/map.ts
  fe/user/tsconfig.json
Labels: BE, FE, release

#74 공연장 목록 조회 - 지도 기반 API 구현
  be/src/main/java/kr/codesquad/jazzmeet/global/config/QueryDslConfig.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/VenueController.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/ShowInfo.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/VenueSearch.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/response/VenueSearchResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/Images.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/Links.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/Venue.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/VenueHours.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/mapper/VenueMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/repository/VenueQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueService.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/vo/VenueSearchData.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/service/VenueServiceTest.java
Labels: feat, BE

#78 공연장 목록 조회 - 검색 기능
  be/src/main/java/kr/codesquad/jazzmeet/show/service/ShowService.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/VenueController.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/ShowInfo.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/response/VenueSearchResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/mapper/VenueMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/repository/VenueQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueService.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/vo/VenueSearchData.java
Labels: feat, BE

#85 공연장 목록 조회 - 공연장 하나만 검색 API 구현
  be/src/main/java/kr/codesquad/jazzmeet/show/entity/Show.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/VenueController.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/ShowInfo.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/repository/VenueQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueService.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/vo/VenueSearchData.java
  be/src/test/java/kr/codesquad/jazzmeet/fixture/ShowFixture.java
  be/src/test/java/kr/codesquad/jazzmeet/fixture/VenueFixture.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/controller/VenueControllerTest.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/repository/VenueQueryRepositoryTest.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/service/VenueServiceTest.java
Labels: feat, BE

#84 공연장 목록 조회 검색 테스트 코드 수정 및 LocalDate 위치 수정
  be/src/main/java/kr/codesquad/jazzmeet/global/error/GlobalExceptionHandler.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/VenueController.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/repository/VenueQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueService.java
  be/src/test/java/kr/codesquad/jazzmeet/fixture/VenueFixture.java
  be/src/test/java/kr/codesquad/jazzmeet/show/service/ShowServiceTest.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/service/VenueServiceTest.java
Labels: refactor, BE, test

#86 현 지도 기준으로 위치 정보 조회
  fe/user/src/apis/venue.ts
  fe/user/src/hooks/useMarkers.ts
  fe/user/src/pages/MapPage/Map/MapSearchButton.tsx
  fe/user/src/pages/MapPage/Map/index.tsx
  fe/user/src/utils/debounce.ts
  fe/user/src/utils/map.ts
Labels: feat, FE

#87 release로 merge
  be/src/main/java/kr/codesquad/jazzmeet/global/error/GlobalExceptionHandler.java
  be/src/main/java/kr/codesquad/jazzmeet/show/entity/Show.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/VenueController.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/ShowInfo.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/repository/VenueQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueService.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/vo/VenueSearchData.java
  be/src/test/java/kr/codesquad/jazzmeet/fixture/ShowFixture.java
  be/src/test/java/kr/codesquad/jazzmeet/fixture/VenueFixture.java
  be/src/test/java/kr/codesquad/jazzmeet/show/service/ShowServiceTest.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/controller/VenueControllerTest.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/repository/VenueQueryRepositoryTest.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/service/VenueServiceTest.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/util/VenueTestUtil.java
  fe/user/src/apis/venue.ts
  fe/user/src/hooks/useMarkers.ts
  fe/user/src/pages/MapPage/Map/MapSearchButton.tsx
  fe/user/src/pages/MapPage/Map/index.tsx
  fe/user/src/utils/debounce.ts
  fe/user/src/utils/map.ts
Labels: BE, FE, release

#88 공연장 상세조회 기능 구현
  be/src/main/java/kr/codesquad/jazzmeet/global/error/statuscode/ErrorCode.java
  be/src/main/java/kr/codesquad/jazzmeet/image/entity/Image.java
  be/src/main/java/kr/codesquad/jazzmeet/image/repository/ImageRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/VenueController.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/response/VenueDetailResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/LinkType.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/Venue.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/VenueHour.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/VenueImage.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/mapper/VenueMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/repository/VenueHourRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/repository/VenueImageRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/repository/VenueQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/repository/VenueRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueService.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/vo/VenueDetail.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/vo/VenueDetailImage.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/vo/VenueDetailLink.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/vo/VenueDetailVenueHour.java
  be/src/test/java/kr/codesquad/jazzmeet/fixture/ImageFixture.java
  be/src/test/java/kr/codesquad/jazzmeet/fixture/VenueFixture.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/controller/VenueControllerTest.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/repository/VenueQueryRepositoryTest.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/service/VenueServiceTest.java
Labels: feat, BE

#65 공연장 상세보기 (캘린더 기능)
  fe/user/src/apis/show.ts
  fe/user/src/pages/MapPage/Panel/VenueDetail/Calendar/getFirstDayAndLastDay.ts
  fe/user/src/pages/MapPage/Panel/VenueDetail/Calendar/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/RestInfo.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/RestInfo/ShowInfo/Calendar.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/RestInfo/ShowInfo/ShowList.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/RestInfo/ShowInfo/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/RestInfo/ShowInfo/useCalendar.ts
  fe/user/src/pages/MapPage/Panel/VenueDetail/RestInfo/index.tsx
  fe/user/src/router.tsx
  fe/user/src/types/api.types.ts
  fe/user/src/utils/dateUtils.ts
Labels: feat, FE

#93 공연장 상세보기 페이지의 공연 상세보기 타입 수정
  fe/user/src/pages/MapPage/Panel/VenueDetail/RestInfo/ShowInfo/ShowList.tsx
  fe/user/src/types/api.types.ts
Labels: fix, FE

#95 진행 중인 공연 시간 포맷 수정 및 메인 페이지 style 수정
  fe/user/src/pages/MainPage/Footer.tsx
  fe/user/src/pages/MainPage/MainSection/CardList/CardListHeader.tsx
  fe/user/src/pages/MainPage/MainSection/CardList/Cards/AroundVenueCard.tsx
  fe/user/src/pages/MainPage/MainSection/CardList/Cards/UpcomingShowCard.tsx
  fe/user/src/pages/MainPage/MainSection/index.tsx
Labels: fix, FE

#97 검색어 자동완성 기능
  fe/user/src/apis/venue.ts
  fe/user/src/components/SearchBar.tsx
  fe/user/src/components/SearchBox/SuggestionBox/SuggestionItem.tsx
  fe/user/src/components/SearchBox/SuggestionBox/index.tsx
  fe/user/src/components/SearchBox/index.tsx
  fe/user/src/layouts/BaseLayout/Header/index.tsx
  fe/user/src/types/api.types.ts
Labels: feat, FE

#99 지도 뷰 기반 공연장 목록 조회
  fe/user/src/apis/venue.ts
  fe/user/src/hooks/useVenueList.ts
  fe/user/src/types/api.types.ts
  fe/user/src/utils/map.ts
Labels: feat, FE

#101 지도 초기 렌더링 시 pin 조회
  fe/user/src/hooks/useMarkers.ts
  fe/user/src/pages/MapPage/Map/index.tsx
Labels: feat, FE

#102 feat: 월간 공연 일자 유무 조회 기능 구현
  be/src/main/java/kr/codesquad/jazzmeet/show/controller/ShowController.java
  be/src/main/java/kr/codesquad/jazzmeet/show/dto/response/ExistShowCalendarResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/show/repository/ShowQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/show/service/ShowService.java
Labels: feat, BE

#105 key 오류 수정 및 ShowList 컴포넌트 주석 제거 후 release merge
  fe/user/src/pages/MapPage/Panel/VenueDetail/BasicInfo.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/Header.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/RestInfo/index.tsx
Labels: fix, release

#115 공연장 목록으로 조회된 리스트 지도에 마커로 렌더링
  fe/user/src/constants/MAP.ts
  fe/user/src/hooks/useMarkers.ts
  fe/user/src/hooks/useVenueList.ts
  fe/user/src/pages/MapPage/Map/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/index.tsx
  fe/user/src/pages/MapPage/Panel/index.tsx
  fe/user/src/pages/MapPage/index.tsx
  fe/user/src/utils/map.ts
Labels: feat, FE

#113 Be/fix/#111 공연장 목록 조회에서 공연 전체 개수 네이밍 수정
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/response/VenueSearchResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/mapper/VenueMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/repository/VenueQueryRepository.java
Labels: fix, BE

#119 문의 글 목록 조회 API 구현
  be/src/main/java/kr/codesquad/jazzmeet/global/error/GlobalExceptionHandler.java
  be/src/main/java/kr/codesquad/jazzmeet/global/error/statuscode/EnumErrorCode.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/controller/InquiryController.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/dto/response/InquirySearch.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/dto/response/InquirySearchResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/entity/Inquiry.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/mapper/InquiryMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/repository/InquiryQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/repository/InquiryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/service/InquiryService.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/util/InquiryCategory.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/util/InquiryStatus.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/vo/InquirySearchData.java
  be/src/test/java/kr/codesquad/jazzmeet/fixture/InquiryFixture.java
  be/src/test/java/kr/codesquad/jazzmeet/inquiry/service/InquiryServiceTest.java
Labels: feat, BE, test

#117 월간 공연 일정 유무 조회 API 구현
  be/src/main/java/kr/codesquad/jazzmeet/global/error/statuscode/ErrorCode.java
  be/src/main/java/kr/codesquad/jazzmeet/global/error/statuscode/ShowErrorCode.java
  be/src/main/java/kr/codesquad/jazzmeet/global/error/statuscode/VenueErrorCode.java
  be/src/main/java/kr/codesquad/jazzmeet/show/controller/ShowController.java
  be/src/main/java/kr/codesquad/jazzmeet/show/dto/response/ShowByDateAndVenueResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/show/mapper/ShowMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/show/repository/ShowQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/show/service/ShowService.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/LinkType.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueService.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/util/VenueUtil.java
  be/src/test/java/kr/codesquad/jazzmeet/show/controller/ShowControllerTest.java
  be/src/test/java/kr/codesquad/jazzmeet/show/repository/ShowRepositoryTest.java
  be/src/test/java/kr/codesquad/jazzmeet/show/service/ShowServiceTest.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/service/VenueServiceTest.java
Labels: fix, feat, BE

#121 공연장 단독 목록, 상세정보
  fe/user/src/apis/venue.ts
  fe/user/src/components/SearchBox/SuggestionBox/SuggestionItem.tsx
  fe/user/src/hooks/useMarkers.ts
  fe/user/src/hooks/useVenueList.ts
  fe/user/src/pages/MainPage/MainSection/CardList/Cards/AroundVenueCard.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/index.tsx
  fe/user/src/pages/MapPage/Panel/index.tsx
  fe/user/src/pages/MapPage/index.tsx
  fe/user/src/stores/usePathHistoryStore.ts
  fe/user/src/types/api.types.ts
Labels: feat, FE

#123 지도 마커 UI, 기능 구현
  fe/user/src/constants/MAP.ts
  fe/user/src/hooks/useMarkers.ts
  fe/user/src/pages/MapPage/Map/index.tsx
  fe/user/src/utils/map.ts
Labels: feat, FE

#127 문의 글 상세 조회
  be/src/main/java/kr/codesquad/jazzmeet/global/error/CustomException.java
  be/src/main/java/kr/codesquad/jazzmeet/global/error/statuscode/InquiryErrorCode.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/controller/InquiryController.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/dto/response/InquiryAnswerDetail.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/dto/response/InquiryDetailResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/entity/Answer.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/entity/Inquiry.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/mapper/InquiryMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/repository/InquiryAnswerRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/repository/InquiryQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/service/InquiryService.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/util/InquiryCategory.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/util/InquiryStatus.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/vo/InquiryDetail.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/VenueController.java
  be/src/test/java/kr/codesquad/jazzmeet/fixture/InquiryFixture.java
  be/src/test/java/kr/codesquad/jazzmeet/inquiry/service/InquiryServiceTest.java
Labels: feat, BE, test

#129 네비게이션 버튼으로 지도페이지 진입 시 공연장 목록 조회
  fe/user/src/hooks/useMarkers.ts
  fe/user/src/hooks/useVenueList.ts
  fe/user/src/pages/MapPage/Map/MapSearchButton.tsx
  fe/user/src/pages/MapPage/Map/index.tsx
  fe/user/src/pages/MapPage/index.tsx
Labels: feat, FE

#131 공연장 등록 기능 구현
  be/src/main/java/kr/codesquad/jazzmeet/global/error/statuscode/ImageErrorCode.java
  be/src/main/java/kr/codesquad/jazzmeet/global/error/statuscode/VenueErrorCode.java
  be/src/main/java/kr/codesquad/jazzmeet/image/controller/ImageController.java
  be/src/main/java/kr/codesquad/jazzmeet/image/dto/response/ImageIdsResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/image/service/ImageService.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/VenueController.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/request/VenueCreateHour.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/request/VenueCreateLink.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/request/VenueCreateRequest.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/response/VenueCreateResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/DayOfWeek.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/Link.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/LinkType.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/Venue.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/VenueHour.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/VenueImage.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/mapper/VenueMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/repository/LinkTypeRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/LinkTypeService.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueFacade.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueService.java
  be/src/test/java/kr/codesquad/jazzmeet/image/service/ImageServiceTest.java
  be/src/test/java/kr/codesquad/jazzmeet/show/repository/ShowRepositoryTest.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/repository/VenueQueryRepositoryTest.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/service/VenueFacadeTest.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/service/VenueServiceTest.java
Labels: feat, BE

#133 방향키로 검색어 목록 선택 기능
  fe/user/src/components/SearchBox/SuggestionBox/SuggestionItem.tsx
  fe/user/src/components/SearchBox/SuggestionBox/index.tsx
  fe/user/src/components/SearchBox/index.tsx
Labels: feat, FE

#138 마커(핀) 렌더링 방식 변경
  fe/user/src/apis/venue.ts
  fe/user/src/hooks/useMapDataUpdater.ts
  fe/user/src/hooks/useMarkers.ts
  fe/user/src/hooks/useVenueList.ts
  fe/user/src/pages/MapPage/Map/MapSearchButton.tsx
  fe/user/src/pages/MapPage/Map/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/ShowDetail/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/index.tsx
  fe/user/src/pages/MapPage/Panel/index.tsx
  fe/user/src/pages/MapPage/index.tsx
  fe/user/src/utils/map.ts
Labels: fix, FE

#143 검색 기능 오류 수정
  fe/user/src/apis/venue.ts
  fe/user/src/hooks/useMapDataUpdater.ts
  fe/user/src/pages/MapPage/Map/MapSearchButton.tsx
  fe/user/src/pages/MapPage/Map/index.tsx
  fe/user/src/pages/MapPage/index.tsx
  fe/user/src/utils/map.ts
Labels: feat, FE

#140 공연 목록 조회 API 구현
  be/build.gradle
  be/src/main/java/kr/codesquad/jazzmeet/show/controller/ShowController.java
  be/src/main/java/kr/codesquad/jazzmeet/show/dto/ShowResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/show/mapper/ShowMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/show/repository/ShowQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/show/service/ShowService.java
  be/src/main/java/kr/codesquad/jazzmeet/show/vo/ShowSummary.java
  be/src/main/java/kr/codesquad/jazzmeet/show/vo/ShowSummaryWithVenue.java
  be/src/main/java/kr/codesquad/jazzmeet/show/vo/ShowWithVenue.java
  be/src/test/java/kr/codesquad/jazzmeet/show/controller/ShowControllerTest.java
  be/src/test/java/kr/codesquad/jazzmeet/show/repository/ShowRepositoryTest.java
  be/src/test/java/kr/codesquad/jazzmeet/show/service/ShowServiceTest.java
Labels: feat, BE, test

#146 공연 페이지 UI
  fe/user/src/assets/icons/CaretLeft.svg
  fe/user/src/assets/icons/CaretRight.svg
  fe/user/src/layouts/BaseLayout/Header/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/RestInfo/ShowInfo/Calendar.tsx
  fe/user/src/pages/ShowPage/CalendarDate/DateController/DateGroup.tsx
  fe/user/src/pages/ShowPage/CalendarDate/DateController/index.tsx
  fe/user/src/pages/ShowPage/CalendarDate/Header/MonthController.tsx
  fe/user/src/pages/ShowPage/CalendarDate/Header/index.tsx
  fe/user/src/pages/ShowPage/CalendarDate/index.tsx
  fe/user/src/pages/ShowPage/ShowContainer/RegionCard/VenueCard.tsx
  fe/user/src/pages/ShowPage/ShowContainer/RegionCard/index.tsx
  fe/user/src/pages/ShowPage/ShowContainer/index.tsx
  fe/user/src/pages/ShowPage/index.tsx
  fe/user/src/router.tsx
Labels: feat, FE

#153 공연 상세 조회 API 구현
  be/src/main/java/kr/codesquad/jazzmeet/global/error/statuscode/ShowErrorCode.java
  be/src/main/java/kr/codesquad/jazzmeet/show/controller/ShowController.java
  be/src/main/java/kr/codesquad/jazzmeet/show/dto/response/ShowDetailResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/show/dto/response/ShowResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/show/mapper/ShowMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/show/repository/ShowRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/show/service/ShowService.java
  be/src/main/java/kr/codesquad/jazzmeet/show/vo/ShowPoster.java
  be/src/test/java/kr/codesquad/jazzmeet/fixture/ShowFixture.java
  be/src/test/java/kr/codesquad/jazzmeet/show/controller/ShowControllerTest.java
  be/src/test/java/kr/codesquad/jazzmeet/show/repository/ShowRepositoryTest.java
  be/src/test/java/kr/codesquad/jazzmeet/show/service/ShowServiceTest.java
Labels: feat, BE, test

#156 공연 페이지 캘린더 기능
  fe/user/src/pages/MapPage/Panel/VenueDetail/RestInfo/ShowInfo/Calendar.tsx
  fe/user/src/pages/ShowPage/CalendarDate/DateController/DateGroup.tsx
  fe/user/src/pages/ShowPage/CalendarDate/DateController/index.tsx
  fe/user/src/pages/ShowPage/CalendarDate/Header/MonthController.tsx
  fe/user/src/pages/ShowPage/CalendarDate/Header/index.tsx
  fe/user/src/pages/ShowPage/CalendarDate/index.tsx
  fe/user/src/utils/dateUtils.ts
Labels: feat, FE

#158 공연장 목록 조회 기능 구현
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/VenueController.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/VenueInfo.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/response/VenueListResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/mapper/VenueMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/repository/VenueQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueFacade.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueService.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/repository/VenueQueryRepositoryTest.java
Labels: feat, BE, test

#168 문의 페이지 기능 구현
  fe/user/src/apis/inquiry.ts
  fe/user/src/pages/InquiryPage/Categories/Category.tsx
  fe/user/src/pages/InquiryPage/Categories/index.tsx
  fe/user/src/pages/InquiryPage/Editor/index.tsx
  fe/user/src/pages/InquiryPage/Editor/validation.ts
  fe/user/src/pages/InquiryPage/Header/index.tsx
  fe/user/src/pages/InquiryPage/InquiryList/Inquiry/index.tsx
  fe/user/src/pages/InquiryPage/InquiryList/InquiryItem/Answer.tsx
  fe/user/src/pages/InquiryPage/InquiryList/InquiryItem/Delete.tsx
  fe/user/src/pages/InquiryPage/InquiryList/InquiryItem/index.tsx
  fe/user/src/pages/InquiryPage/InquiryList/index.tsx
  fe/user/src/pages/InquiryPage/TabList.tsx
  fe/user/src/pages/InquiryPage/index.tsx
  fe/user/src/types/api.types.ts
  fe/user/src/types/inquiry.types.ts
  fe/user/src/utils/dateUtils.ts
Labels: feat, FE

#169 선택된 날짜의 공연 목록 조회
  fe/user/src/apis/show.ts
  fe/user/src/pages/MapPage/Panel/VenueDetail/RestInfo/ShowInfo/Calendar.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/RestInfo/ShowInfo/index.tsx
  fe/user/src/pages/ShowPage/CalendarDate/DateController/DateGroup.tsx
  fe/user/src/pages/ShowPage/CalendarDate/DateController/index.tsx
  fe/user/src/pages/ShowPage/ShowContainer/RegionCard/VenueCard.tsx
  fe/user/src/pages/ShowPage/ShowContainer/RegionCard/index.tsx
  fe/user/src/pages/ShowPage/ShowContainer/index.tsx
  fe/user/src/stores/useShowStore.ts
  fe/user/src/types/api.types.ts
  fe/user/src/utils/dateUtils.ts
Labels: feat, FE

#166 공연 수정 API 구현
  be/src/main/java/kr/codesquad/jazzmeet/show/controller/ShowController.java
  be/src/main/java/kr/codesquad/jazzmeet/show/dto/request/RegisterShowRequest.java
  be/src/main/java/kr/codesquad/jazzmeet/show/dto/response/ShowDetailResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/show/entity/Show.java
  be/src/main/java/kr/codesquad/jazzmeet/show/mapper/ShowMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/show/repository/ShowQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/show/service/ShowService.java
  be/src/test/java/kr/codesquad/jazzmeet/show/controller/ShowControllerTest.java
  be/src/test/java/kr/codesquad/jazzmeet/show/service/ShowServiceTest.java
Labels: feat, BE, test

#173 Be/hotfix/error message
  be/src/main/java/kr/codesquad/jazzmeet/global/error/ErrorResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/global/error/GlobalExceptionHandler.java
Labels: release

#176 release로 merge
  be/src/main/java/kr/codesquad/jazzmeet/global/error/ErrorResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/global/error/GlobalExceptionHandler.java
Labels: release

#171 공연장 관련 코드 리팩토링
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/VenueController.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/annotation/Latitude.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/annotation/LatitudeValidator.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/annotation/Longitude.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/annotation/LongitudeValidator.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/annotation/RangeCoordinates.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/annotation/RangeCoordinatesValidator.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/request/RangeCoordinatesRequest.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/request/VenueCreateRequest.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/request/VenueUpdateRequest.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/response/VenueSearchResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/mapper/VenueMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueFacade.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueService.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/util/LocationUtil.java
  be/src/test/java/kr/codesquad/jazzmeet/fixture/VenueFixture.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/repository/VenueQueryRepositoryTest.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/service/VenueServiceTest.java
Labels: refactor, BE

#180 문의 기능 오류 수정
  fe/user/src/apis/inquiry.ts
  fe/user/src/constants/LIMITS.ts
  fe/user/src/pages/InquiryPage/Editor/index.tsx
  fe/user/src/pages/InquiryPage/Editor/validation.ts
  fe/user/src/pages/InquiryPage/InquiryList/InquiryItem/Delete.tsx
  fe/user/src/utils/validation.ts
Labels: fix, FE

#181 문의 답변 삭제
  be/src/main/java/kr/codesquad/jazzmeet/global/error/GlobalExceptionHandler.java
  be/src/main/java/kr/codesquad/jazzmeet/global/error/statuscode/ErrorCode.java
  be/src/main/java/kr/codesquad/jazzmeet/global/error/statuscode/InquiryErrorCode.java
  be/src/main/java/kr/codesquad/jazzmeet/global/util/PasswordEncoder.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/controller/InquiryController.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/dto/request/answer/InquiryAnswerSaveRequest.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/dto/request/answer/InquiryAnswerUpdateRequest.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/dto/response/InquiryDetailResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/dto/response/answer/InquiryAnswerDetail.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/dto/response/answer/InquiryAnswerSaveResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/dto/response/answer/InquiryAnswerUpdateResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/entity/Inquiry.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/mapper/InquiryMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/repository/InquiryAnswerRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/repository/InquiryQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/service/InquiryService.java
  be/src/test/java/kr/codesquad/jazzmeet/fixture/InquiryFixture.java
  be/src/test/java/kr/codesquad/jazzmeet/inquiry/service/InquiryServiceTest.java
Labels: fix, feat, BE, test

#182 관리자 계정 생성 API 구현
  be/src/main/java/kr/codesquad/jazzmeet/admin/AdminMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
  be/src/main/java/kr/codesquad/jazzmeet/admin/dto/request/SignUpAdminRequest.java
  be/src/main/java/kr/codesquad/jazzmeet/admin/entity/Admin.java
  be/src/main/java/kr/codesquad/jazzmeet/admin/entity/UserRole.java
  be/src/main/java/kr/codesquad/jazzmeet/admin/repository/AdminRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/admin/service/AdminService.java
  be/src/main/java/kr/codesquad/jazzmeet/global/error/statuscode/AdminErrorCode.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/repository/InquiryQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/show/service/ShowService.java
  be/src/test/java/kr/codesquad/jazzmeet/admin/controller/AdminControllerTest.java
  be/src/test/java/kr/codesquad/jazzmeet/admin/service/AdminServiceTest.java
  be/src/test/java/kr/codesquad/jazzmeet/fixture/AdminFixture.java
Labels: feat, BE, test

#183 S3에서 필요없는 이미지 삭제 기능
  be/src/main/java/kr/codesquad/jazzmeet/JazzMeetApplication.java
  be/src/main/java/kr/codesquad/jazzmeet/global/error/statuscode/ImageErrorCode.java
  be/src/main/java/kr/codesquad/jazzmeet/image/entity/Image.java
  be/src/main/java/kr/codesquad/jazzmeet/image/mapper/ImageMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/image/repository/ImageQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/image/repository/S3ImageHandler.java
  be/src/main/java/kr/codesquad/jazzmeet/image/service/CloudService.java
  be/src/main/java/kr/codesquad/jazzmeet/image/service/ImageScheduler.java
  be/src/main/java/kr/codesquad/jazzmeet/image/service/ImageService.java
  be/src/main/java/kr/codesquad/jazzmeet/show/entity/Show.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/Venue.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueFacade.java
  be/src/test/java/kr/codesquad/jazzmeet/fixture/ImageFixture.java
  be/src/test/java/kr/codesquad/jazzmeet/fixture/ShowFixture.java
  be/src/test/java/kr/codesquad/jazzmeet/image/repository/ImageRepositoryTest.java
  be/src/test/java/kr/codesquad/jazzmeet/image/repository/S3ImageHandlerTest.java
  be/src/test/java/kr/codesquad/jazzmeet/image/service/ImageServiceTest.java
Labels: feat, BE

#192 지도 관련 오류 수정
  fe/user/src/apis/venue.ts
  fe/user/src/components/SearchBox/index.tsx
  fe/user/src/constants/MAP.ts
  fe/user/src/hooks/useMapDataUpdater.ts
  fe/user/src/layouts/BaseLayout/Header/index.tsx
  fe/user/src/pages/MapPage/Map/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/index.tsx
  fe/user/src/pages/MapPage/index.tsx
  fe/user/src/types/api.types.ts
  fe/user/src/utils/map.ts
Labels: fix, refactor, FE

#197 feat: 타임존 Asia/Seoul로 변경
  be/Dockerfile
Labels: BE

#190 Be/fix/#189 공연장 목록 조회 검색, 지도기반 에서 null 이 반환되는 문제
  be/src/main/java/kr/codesquad/jazzmeet/image/entity/Image.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/mapper/VenueMapper.java
Labels: fix, BE

#199 release로 merge
  be/src/main/java/kr/codesquad/jazzmeet/image/entity/Image.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/mapper/VenueMapper.java
Labels: release

#194 관리자 페이지 UI 구현
  fe/user/src/apis/inquiry.ts
  fe/user/src/apis/show.ts
  fe/user/src/apis/venue.ts
  fe/user/src/assets/icons/JazzMeet.svg
  fe/user/src/components/Sidebar/SidebarItem.tsx
  fe/user/src/constants/INQUIRY.ts
  fe/user/src/hooks/useMapDataUpdater.ts
  fe/user/src/layouts/AdminLayout/Sidebar.tsx
  fe/user/src/layouts/AdminLayout/index.tsx
  fe/user/src/pages/AdminPage/InquiriesPage/index.tsx
  fe/user/src/pages/AdminPage/ShowsPage/index.tsx
  fe/user/src/pages/AdminPage/VenuesPage/index.tsx
  fe/user/src/pages/InquiryPage/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/VenueItem/Description.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/VenueItem/index.tsx
  fe/user/src/router.tsx
  fe/user/src/styles/designSystem.ts
  fe/user/src/types/api.types.ts
  fe/user/src/types/map.types.ts
  fe/user/src/utils/dateUtils.ts
  fe/user/src/utils/map.ts
Labels: feat, FE

#196 검색창 기능 오류 수정
  fe/user/src/components/SearchBox/SuggestionBox/SuggestionItem.tsx
  fe/user/src/components/SearchBox/SuggestionBox/index.tsx
  fe/user/src/components/SearchBox/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/BasicInfo.tsx
  fe/user/src/types/svg.d.ts
  fe/user/src/types/svgr.d.ts
  fe/user/tsconfig.json
Labels: fix, FE

#202 관리자 페이지 클라이언트 코드 제거
  fe/user/src/components/Sidebar/SidebarItem.tsx
  fe/user/src/layouts/AdminLayout/Sidebar.tsx
  fe/user/src/layouts/AdminLayout/index.tsx
  fe/user/src/pages/AdminPage/InquiriesPage/index.tsx
  fe/user/src/pages/AdminPage/ShowsPage/index.tsx
  fe/user/src/pages/AdminPage/VenuesPage/index.tsx
  fe/user/src/router.tsx
Labels: FE, chore
