Repository jazz-meet/jazz-meet, pull requests merged in 2023-12, with the labels that each got.

#207 공연장 목록 QA 피드백 반영
  fe/user/src/pages/MapPage/Panel/VenueList/VenueItem/Description.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/index.tsx
Labels: fix, FE

#221 주소 검색 response 오타 수정
  be/src/main/java/kr/codesquad/jazzmeet/address/controller/AddressController.java
  be/src/main/java/kr/codesquad/jazzmeet/address/dto/response/AddressResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/address/dto/response/AddressSearchResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/address/service/AddressService.java
Labels: fix, BE

#222 release로 merge
  be/src/main/java/kr/codesquad/jazzmeet/address/controller/AddressController.java
  be/src/main/java/kr/codesquad/jazzmeet/address/dto/response/AddressResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/address/dto/response/AddressSearchResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/address/service/AddressService.java
Labels: release

#217 로고 변경
  fe/user/src/assets/icons/JazzMeet.svg
  fe/user/src/layouts/BaseLayout/Header/index.tsx
  fe/user/src/pages/InquiryPage/InquiryList/InquiryItem/Answer.tsx
  fe/user/src/pages/MainPage/Footer.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/Images/PreviewImages.tsx
Labels: feat, FE

#219 문의글 클릭시 오류 수정
  fe/user/src/pages/InquiryPage/InquiryList/InquiryItem/index.tsx
  fe/user/src/types/api.types.ts
Labels: fix, FE

#224 문의 글 목록 조회 시 status 필터 추가
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/controller/InquiryController.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/repository/InquiryQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/service/InquiryService.java
  be/src/test/java/kr/codesquad/jazzmeet/inquiry/service/InquiryServiceTest.java
Labels: feat, BE

#230 공연장 수정 시 이미지가 반환되지 않는 오류 수정
  be/src/main/java/kr/codesquad/jazzmeet/image/service/ImageService.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueFacade.java
Labels: fix, BE

#231 release로 merge
  be/src/main/java/kr/codesquad/jazzmeet/image/service/ImageService.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/controller/InquiryController.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/repository/InquiryQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/service/InquiryService.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueFacade.java
  be/src/test/java/kr/codesquad/jazzmeet/inquiry/service/InquiryServiceTest.java
  fe/user/src/assets/icons/JazzMeet.svg
  fe/user/src/layouts/BaseLayout/Header/index.tsx
  fe/user/src/pages/InquiryPage/InquiryList/InquiryItem/Answer.tsx
  fe/user/src/pages/InquiryPage/InquiryList/InquiryItem/index.tsx
  fe/user/src/pages/MainPage/Footer.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/Images/PreviewImages.tsx
  fe/user/src/types/api.types.ts
Labels: release

#234 공연장 업데이트 시 공연장 설명 제한 수정
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/request/VenueUpdateRequest.java
Labels: fix, BE

#235 공연장 업데이트 시 공연장 설명 길이 제한 수정 반영
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/request/VenueUpdateRequest.java
Labels: BE, release

#228 문의 답변 일자 포맷팅 후 렌더링
  fe/user/src/pages/InquiryPage/InquiryList/InquiryItem/Answer.tsx
Labels: fix, FE

#226 문의페이지 문의 검색 필터 제거 버튼 구현
  fe/user/src/pages/InquiryPage/Header/index.tsx
  fe/user/src/pages/InquiryPage/index.tsx
Labels: feat, FE

#240 지도 '내 위치로 이동' 버튼 UI 및 기능 구현
  fe/user/src/assets/icons/MyLocation.svg
  fe/user/src/constants/COORDINATE.ts
  fe/user/src/hooks/useMapDataUpdater.ts
  fe/user/src/pages/MainPage/MainSection/AroundVenus.tsx
  fe/user/src/pages/MapPage/Map/index.tsx
  fe/user/src/pages/MapPage/index.tsx
  fe/user/src/utils/map.ts
Labels: feat, FE

#242 메인페이지 스켈레톤 UI 구현
  fe/user/src/pages/MainPage/MainSection/AroundVenus.tsx
  fe/user/src/pages/MainPage/MainSection/CardList/CardListSkeleton.tsx
  fe/user/src/pages/MainPage/MainSection/UpcomingShows.tsx
  fe/user/src/styles/designSystem.ts
Labels: feat, FE

#247 진행 중인 공연 조회 response 수정
  be/src/main/java/kr/codesquad/jazzmeet/show/dto/response/UpcomingShowResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/show/mapper/ShowMapper.java
  fe/user/src/pages/MainPage/MainSection/CardList/Cards/UpcomingShowCard.tsx
  fe/user/src/types/api.types.ts
Labels: fix, BE, FE

#252 모바일 뷰 레이아웃 구현 및 검색창 UI 기능 구현
  fe/user/src/components/SearchBox/index.tsx
  fe/user/src/constants/Z_INDEX.ts
  fe/user/src/layouts/MobileLayout/BottomNavigation.tsx
  fe/user/src/layouts/MobileLayout/Header.tsx
  fe/user/src/layouts/MobileLayout/index.tsx
  fe/user/src/layouts/PCLayout/Header.tsx
  fe/user/src/layouts/PCLayout/index.tsx
  fe/user/src/layouts/index.tsx
  fe/user/src/router.tsx
Labels: feat, FE

#251 문의 페이지 모바일 UI 적용
  be/src/main/java/kr/codesquad/jazzmeet/show/dto/response/UpcomingShowResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/show/mapper/ShowMapper.java
  fe/user/src/pages/InquiryPage/Editor/index.tsx
  fe/user/src/pages/InquiryPage/Header/index.tsx
  fe/user/src/pages/InquiryPage/InquiryList/InquiryItem/Mobile.tsx
  fe/user/src/pages/InquiryPage/InquiryList/InquiryItem/PC.tsx
  fe/user/src/pages/InquiryPage/InquiryList/InquiryItem/index.tsx
  fe/user/src/pages/InquiryPage/index.tsx
  fe/user/src/pages/MainPage/MainSection/CardList/Cards/UpcomingShowCard.tsx
  fe/user/src/types/api.types.ts
Labels: feat, refactor, FE

#255 첫 렌더링시 device type 체크 못하는 이슈 및 SearchBox UI 수정
  fe/user/src/components/DeviceTypeChecker.tsx
  fe/user/src/layouts/MobileLayout/Header.tsx
  fe/user/src/stores/useDeviceTypeStore.ts
Labels: fix, FE

#257 공연장 페이지 모바일 뷰 구현
  fe/user/src/hooks/useMapDataUpdater.ts
  fe/user/src/pages/MapPage/Map/index.tsx
  fe/user/src/pages/MapPage/Panel/index.tsx
  fe/user/src/pages/MapPage/index.tsx
  fe/user/src/types/device.types.ts
Labels: feat, FE

#214 관리자 로그인
  be/build.gradle
  be/src/main/java/kr/codesquad/jazzmeet/JazzMeetApplication.java
  be/src/main/java/kr/codesquad/jazzmeet/admin/AdminMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
  be/src/main/java/kr/codesquad/jazzmeet/admin/dto/request/LoginAdminRequest.java
  be/src/main/java/kr/codesquad/jazzmeet/admin/dto/request/ReissueAdminRequest.java
  be/src/main/java/kr/codesquad/jazzmeet/admin/dto/response/LoginAdminResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/admin/entity/Admin.java
  be/src/main/java/kr/codesquad/jazzmeet/admin/repository/AdminRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/admin/service/AdminService.java
  be/src/main/java/kr/codesquad/jazzmeet/global/config/WebConfig.java
  be/src/main/java/kr/codesquad/jazzmeet/global/error/statuscode/AdminErrorCode.java
  be/src/main/java/kr/codesquad/jazzmeet/global/error/statuscode/ErrorCode.java
  be/src/main/java/kr/codesquad/jazzmeet/global/jwt/Jwt.java
  be/src/main/java/kr/codesquad/jazzmeet/global/jwt/JwtProperties.java
  be/src/main/java/kr/codesquad/jazzmeet/global/jwt/JwtProvider.java
  be/src/main/java/kr/codesquad/jazzmeet/global/permission/AdminAuth.java
  be/src/main/java/kr/codesquad/jazzmeet/global/permission/AdminResolver.java
  be/src/main/java/kr/codesquad/jazzmeet/global/permission/Permission.java
  be/src/main/java/kr/codesquad/jazzmeet/global/permission/PermissionInterceptor.java
  be/src/test/java/kr/codesquad/jazzmeet/admin/controller/AdminControllerTest.java
  be/src/test/java/kr/codesquad/jazzmeet/admin/service/AdminServiceTest.java
  be/src/test/java/kr/codesquad/jazzmeet/global/jwt/JwtProviderTest.java
Labels: feat, BE, test

#263 반응형 UI 리팩토링
  fe/user/src/hooks/useMapDataUpdater.ts
  fe/user/src/layouts/index.tsx
  fe/user/src/pages/InquiryPage/Editor/index.tsx
  fe/user/src/pages/InquiryPage/Header/index.tsx
  fe/user/src/pages/InquiryPage/InquiryList/InquiryItem/index.tsx
  fe/user/src/pages/InquiryPage/index.tsx
  fe/user/src/pages/MapPage/ToggleRenderTypeButton.tsx
  fe/user/src/pages/MapPage/index.tsx
  fe/user/src/stores/useDeviceTypeStore.ts
  fe/user/src/types/device.types.ts
Labels: refactor, FE

#266 배너 UI 사이즈 조정
  fe/user/src/pages/MainPage/Banner/SwiperComponent.tsx
Labels: fix, FE
