Repository jazz-meet/jazz-meet, pull requests merged in 2023-10, with the labels that each got.

#4 user app 세팅 및 API 요청 구현
  fe/user/index.html
  fe/user/src/apis/fetchData.ts
  fe/user/src/apis/venue/index.ts
  fe/user/src/apis/venue/types.ts
  fe/user/src/constants/ENV_VARIABLES.ts
  fe/user/src/types/map.ts
  fe/user/src/utils/getQueryString.ts
  fe/user/tsconfig.json
Labels: feat, FE

#14 프로젝트 환경 구축
  .gitignore
  be/build.gradle
  be/src/main/java/kr/codesquad/jazzmeet/admin/entity/Admin.java
  be/src/main/java/kr/codesquad/jazzmeet/global/config/WebConfig.java
  be/src/main/java/kr/codesquad/jazzmeet/global/error/statuscode/ErrorCode.java
  be/src/main/java/kr/codesquad/jazzmeet/image/entity/Image.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/entity/Answer.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/entity/Inquiry.java
  be/src/main/java/kr/codesquad/jazzmeet/show/entity/Show.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/Images.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/Link.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/LinkType.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/Links.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/Venue.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/VenueImage.java
Labels: feat, build, BE

#16 메인페이지 UI 구현
  fe/user/package-lock.json
  fe/user/package.json
  fe/user/src/components/SearchBar.tsx
  fe/user/src/layouts/BaseLayout/Header.tsx
  fe/user/src/layouts/BaseLayout/Header/index.tsx
  fe/user/src/layouts/BaseLayout/index.tsx
  fe/user/src/pages/MainPage/Banner/SwiperComponent.tsx
  fe/user/src/pages/MainPage/Banner/index.tsx
  fe/user/src/pages/MainPage/Footer.tsx
  fe/user/src/pages/MainPage/MainSection/AroundVenus.tsx
  fe/user/src/pages/MainPage/MainSection/CardList/CardListHeader.tsx
  fe/user/src/pages/MainPage/MainSection/CardList/Cards/Card.tsx
  fe/user/src/pages/MainPage/MainSection/CardList/Cards/index.tsx
  fe/user/src/pages/MainPage/MainSection/CardList/index.tsx
  fe/user/src/pages/MainPage/MainSection/OngoingShows.tsx
  fe/user/src/pages/MainPage/MainSection/index.tsx
  fe/user/src/pages/MainPage/index.tsx
  fe/user/vite.config.ts
Labels: feat, FE

#17 문의페이지 UI
  fe/user/src/App.tsx
  fe/user/src/components/AutoSizingTextArea.tsx
  fe/user/src/components/PaginationBox.tsx
  fe/user/src/components/SearchBar.tsx
  fe/user/src/layouts/BaseLayout/index.tsx
  fe/user/src/pages/InquiryPage/Editor/index.tsx
  fe/user/src/pages/InquiryPage/Header/index.tsx
  fe/user/src/pages/InquiryPage/InquiryList/Inquiry/Answer.tsx
  fe/user/src/pages/InquiryPage/InquiryList/Inquiry/index.tsx
  fe/user/src/pages/InquiryPage/InquiryList/index.tsx
  fe/user/src/pages/InquiryPage/TabList.tsx
  fe/user/src/pages/InquiryPage/index.tsx
  fe/user/src/pages/MainPage/Banner/index.tsx
  fe/user/vite.config.ts
Labels: feat, FE

#21 검색어 자동 완성 목록 조회 기능 구현
  be/build.gradle
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/VenueController.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/response/VenueAutocompleteResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/Link.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/Venue.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/mapper/VenueMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/repository/VenueRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueService.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/util/VenueUtil.java
  be/src/test/java/kr/codesquad/jazzmeet/IntegrationTestSupport.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/service/VenueServiceTest.java
Labels: feat, BE

#31 테스트 없이 빌드 배포
  .github/workflows/cicd.yml
Labels: BE

#32 공연장 목록 UI
  fe/user/package-lock.json
  fe/user/package.json
  fe/user/src/App.tsx
  fe/user/src/components/DatePicker.tsx
  fe/user/src/components/PaginationBox.tsx
  fe/user/src/components/PillShapeButton.tsx
  fe/user/src/layouts/BaseLayout/Header/index.tsx
  fe/user/src/pages/InquiryPage/index.tsx
  fe/user/src/pages/MapPage/Map/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/Header/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/VenueItem/Description.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/VenueItem/Thumbnail.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/VenueItem/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/index.tsx
  fe/user/src/pages/MapPage/Panel/index.tsx
  fe/user/src/pages/MapPage/index.tsx
Labels: feat, FE

#33 공연장 상세정보 UI
  fe/user/src/assets/icons/Backpack.svg
  fe/user/src/assets/icons/BeerBottle.svg
  fe/user/src/assets/icons/Buildings.svg
  fe/user/src/layouts/BaseLayout/Header/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/BasicInfo.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/Calendar/getFirstDayAndLastDay.ts
  fe/user/src/pages/MapPage/Panel/VenueDetail/Calendar/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/Header.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/PreviewImages.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/RestInfo.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/Tabs/Tab.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/Tabs/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/index.tsx
  fe/user/src/pages/MapPage/Panel/index.tsx
  fe/user/src/router.tsx
Labels: feat, FE

#34 지도 페이지 UI
  fe/user/package-lock.json
  fe/user/package.json
  fe/user/src/App.tsx
  fe/user/src/assets/icons/Backpack.svg
  fe/user/src/assets/icons/BeerBottle.svg
  fe/user/src/assets/icons/Buildings.svg
  fe/user/src/components/DatePicker.tsx
  fe/user/src/components/PaginationBox.tsx
  fe/user/src/components/PillShapeButton.tsx
  fe/user/src/layouts/BaseLayout/Header/index.tsx
  fe/user/src/layouts/BaseLayout/index.tsx
  fe/user/src/pages/InquiryPage/index.tsx
  fe/user/src/pages/MapPage/Map/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/BasicInfo.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/Calendar/getFirstDayAndLastDay.ts
  fe/user/src/pages/MapPage/Panel/VenueDetail/Calendar/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/Header.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/PreviewImages.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/RestInfo.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/Tabs/Tab.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/Tabs/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/Header/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/VenueItem/Description.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/VenueItem/Thumbnail.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/VenueItem/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/index.tsx
  fe/user/src/pages/MapPage/Panel/index.tsx
  fe/user/src/pages/MapPage/index.tsx
  fe/user/src/router.tsx
Labels: feat, FE

#35 3주차 UI 작업 release
  fe/user/package-lock.json
  fe/user/package.json
  fe/user/src/App.tsx
  fe/user/src/assets/icons/Backpack.svg
  fe/user/src/assets/icons/BeerBottle.svg
  fe/user/src/assets/icons/Buildings.svg
  fe/user/src/components/DatePicker.tsx
  fe/user/src/components/PaginationBox.tsx
  fe/user/src/components/PillShapeButton.tsx
  fe/user/src/layouts/BaseLayout/Header/index.tsx
  fe/user/src/layouts/BaseLayout/index.tsx
  fe/user/src/pages/InquiryPage/index.tsx
  fe/user/src/pages/MapPage/Map/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/BasicInfo.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/Calendar/getFirstDayAndLastDay.ts
  fe/user/src/pages/MapPage/Panel/VenueDetail/Calendar/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/Header.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/PreviewImages.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/RestInfo.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/Tabs/Tab.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/Tabs/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/Header/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/VenueItem/Description.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/VenueItem/Thumbnail.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/VenueItem/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/index.tsx
  fe/user/src/pages/MapPage/Panel/index.tsx
  fe/user/src/pages/MapPage/index.tsx
  fe/user/src/router.tsx
Labels: feat, FE

#36 feat: 진행 중인 공연 목록 조회 기능 구현
  be/src/main/java/kr/codesquad/jazzmeet/image/entity/Image.java
  be/src/main/java/kr/codesquad/jazzmeet/show/controller/ShowController.java
  be/src/main/java/kr/codesquad/jazzmeet/show/dto/response/UpcomingShowResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/show/entity/Show.java
  be/src/main/java/kr/codesquad/jazzmeet/show/mapper/ShowMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/show/repository/ShowRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/show/service/ShowService.java
  be/src/test/java/kr/codesquad/jazzmeet/show/service/ShowServiceTest.java
Labels: feat, BE

#40 주변 공연장 목록 조회 기능(미완성)
  be/build.gradle
  be/src/main/java/kr/codesquad/jazzmeet/global/config/QueryDslConfig.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/VenueController.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/dto/response/NearbyVenueResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/Venue.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/mapper/VenueMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/repository/VenueQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/repository/VenueRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueService.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/util/VenueUtil.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/vo/NearbyVenue.java
Labels: feat, BE

#37 공연장 상세보기 UI
  fe/user/src/pages/MapPage/Map/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/Images/ImageDetail.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/Images/PreviewImages.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/Images/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/RestInfo.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/ShowDetail/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/index.tsx
  fe/user/src/pages/MapPage/Panel/index.tsx
  fe/user/src/pages/MapPage/index.tsx
  fe/user/src/router.tsx
Labels: feat, FE

#41 지도 페이지 UI
  fe/user/src/pages/MapPage/Map/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/Images/ImageDetail.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/Images/PreviewImages.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/Images/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/RestInfo.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/ShowDetail/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/index.tsx
  fe/user/src/pages/MapPage/Panel/index.tsx
  fe/user/src/pages/MapPage/index.tsx
  fe/user/src/router.tsx
Labels: feat, FE

#49 프론트 빌드 에러 수정
  fe/user/src/pages/InquiryPage/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/index.tsx
Labels: fix, FE

#51 핀목록조회 검색 피드백 반영
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/VenueController.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/mapper/VenueMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueService.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/repository/VenueQueryRepositoryTest.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/service/VenueServiceTest.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/util/VenueTestUtil.java
Labels: refactor, BE

#53 feat: VenueHour 테이블 추가
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/Venue.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/VenueHour.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/VenueHours.java
Labels: feat, BE

#54 메인 페이지 기능 구현 (배너, 공연장, 공연)
  fe/user/src/apis/show.ts
  fe/user/src/apis/venue.ts
  fe/user/src/apis/venue/types.ts
  fe/user/src/constants/COORDINATE.ts
  fe/user/src/constants/ENV_VARIABLES.ts
  fe/user/src/pages/MainPage/Banner/SwiperComponent.tsx
  fe/user/src/pages/MainPage/MainSection/AroundVenus.tsx
  fe/user/src/pages/MainPage/MainSection/CardList/Cards/AroundVenueCard.tsx
  fe/user/src/pages/MainPage/MainSection/CardList/Cards/Card.tsx
  fe/user/src/pages/MainPage/MainSection/CardList/Cards/UpcomingShowCard.tsx
  fe/user/src/pages/MainPage/MainSection/CardList/Cards/index.tsx
  fe/user/src/pages/MainPage/MainSection/OngoingShows.tsx
  fe/user/src/pages/MainPage/MainSection/UpcomingShows.tsx
  fe/user/src/pages/MainPage/MainSection/index.tsx
  fe/user/src/types/api.types.ts
  fe/user/src/types/map.types.ts
Labels: feat, FE

#56 공연장 목록 조회 기능 추가
  fe/user/src/apis/venue.ts
  fe/user/src/constants/ENV_VARIABLES.ts
  fe/user/src/hooks/useVenueList.ts
  fe/user/src/pages/MapPage/Panel/VenueList/Header/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/VenueItem/Description.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/VenueItem/Thumbnail.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/VenueItem/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/index.tsx
  fe/user/src/pages/MapPage/Panel/index.tsx
  fe/user/src/pages/MapPage/index.tsx
  fe/user/src/types/api.types.ts
  fe/user/src/utils/formatTime.ts
Labels: feat, FE
