Repository jazz-meet/jazz-meet, pull requests merged in 2024-01, with the labels that each got.

#271 메인 페이지 LCP 최적화
  fe/user/src/pages/MainPage/Banner/index.tsx
Labels: fix, FE

#272 지도페이지 버튼 레이아웃 수정
  fe/user/src/pages/MapPage/Map/MapSearchButton.tsx
  fe/user/src/pages/MapPage/index.tsx
  fe/user/src/styles/reset.css
Labels: fix, FE

#275 메인페이지 카드리스트 반응형 레이아웃 적용
  fe/user/src/pages/MainPage/MainSection/CardList/CardListSkeleton.tsx
Labels: fix, FE

#277 공연장 상세보기에서 뒤로가기 버튼 클릭시 리스트 재조회 현상 수정
  fe/user/src/pages/MapPage/Panel/VenueDetail/index.tsx
Labels: fix, FE

#279 패널 VenueItem 반응형 레이아웃 적용
  fe/user/src/pages/MapPage/Panel/VenueList/VenueItem/Thumbnail.tsx
  fe/user/src/pages/MapPage/Panel/VenueList/VenueItem/index.tsx
Labels: fix, FE

#284 사용자 줌 이벤트 시 '현 지도에서 검색' 버튼 렌더링
  fe/user/src/pages/MapPage/Map/index.tsx
Labels: fix, FE

#291 refactor: 웹 드라이버 자동 설치 및 자동 버전 업데이트
  be/build.gradle
  be/src/main/java/kr/codesquad/jazzmeet/global/util/WebDriverUtil.java
Labels: refactor, BE

#292 release로 merge
  be/build.gradle
  be/src/main/java/kr/codesquad/jazzmeet/global/util/WebDriverUtil.java
  fe/user/src/pages/MapPage/Map/index.tsx
Labels: BE, FE, release

#297 지도 페이지 스크롤 생기지 않도록 수정
  fe/user/src/pages/MapPage/Map/index.tsx
  fe/user/src/pages/MapPage/index.tsx
Labels: fix, FE

#299 infra: docker image os 변경 및 크롬 설치 명령 추가
  be/Dockerfile
  be/src/main/java/kr/codesquad/jazzmeet/show/controller/ShowController.java
Labels: fix, build, BE

#300 release로 merge
  be/Dockerfile
  be/src/main/java/kr/codesquad/jazzmeet/show/controller/ShowController.java
  fe/user/src/pages/MainPage/MainSection/CardList/Cards/UpcomingShowCard.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/RestInfo/ShowInfo/ShowList.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/RestInfo/ShowInfo/index.tsx
  fe/user/src/pages/MapPage/Panel/VenueDetail/RestInfo/ShowInfo/useCalendar.ts
  fe/user/src/pages/MapPage/Panel/VenueDetail/ShowDetail/index.tsx
  fe/user/src/stores/useShowDetailStore.ts
Labels: fix, BE, FE, release

#301 fix: 암묵적 대기, 대기 시간 할당
  be/src/main/java/kr/codesquad/jazzmeet/show/service/ShowScheduler.java
Labels: fix, BE

#302 release로 merge
  be/src/main/java/kr/codesquad/jazzmeet/show/service/ShowScheduler.java
Labels: fix, BE, release

#303 fix: 대기 시간 추가
  be/src/main/java/kr/codesquad/jazzmeet/show/repository/WebCrawler.java
  be/src/main/java/kr/codesquad/jazzmeet/show/service/ShowScheduler.java
Labels: fix, BE

#304 release로 merge
  be/src/main/java/kr/codesquad/jazzmeet/show/repository/WebCrawler.java
  be/src/main/java/kr/codesquad/jazzmeet/show/service/ShowScheduler.java
Labels: BE, release

#305 fix: 크롤링 url 이동 대기시간 추가
  be/src/main/java/kr/codesquad/jazzmeet/show/repository/WebCrawler.java
Labels: fix, BE

#306 release로 merge
  be/src/main/java/kr/codesquad/jazzmeet/show/repository/WebCrawler.java
Labels: fix, BE, release

#307 공연 관련 쿼리 개선
  be/src/main/java/kr/codesquad/jazzmeet/image/entity/Image.java
  be/src/main/java/kr/codesquad/jazzmeet/image/repository/S3ImageHandler.java
  be/src/main/java/kr/codesquad/jazzmeet/show/dto/response/UpcomingShowResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/show/repository/ShowQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/show/repository/ShowRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/show/service/ShowService.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueFacade.java
Labels: refactor, BE
