Repository jazz-meet/jazz-meet, pull requests merged in 2024-02, with the labels that each got.

#298 공연 페이지에서 공연장 클릭 시 해당 공연의 상세페이지에서 클릭한 날짜의 공연 목록을 보여주는 기능
  fe/user/src/pages/ShowPage/ShowContainer/RegionCard/VenueCard.tsx
Labels: feat, FE

#310 release로 merge
  be/src/main/java/kr/codesquad/jazzmeet/image/entity/Image.java
  be/src/main/java/kr/codesquad/jazzmeet/image/repository/S3ImageHandler.java
  be/src/main/java/kr/codesquad/jazzmeet/show/dto/response/UpcomingShowResponse.java
  be/src/main/java/kr/codesquad/jazzmeet/show/repository/ShowQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/show/repository/ShowRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/show/service/ShowService.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueFacade.java
  fe/user/src/pages/ShowPage/ShowContainer/RegionCard/VenueCard.tsx
Labels: BE, FE, release

#313 공연장 상세조회 쿼리 개선
  be/src/main/java/kr/codesquad/jazzmeet/show/mapper/ShowMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/show/service/ShowService.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/repository/VenueQueryRepository.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/vo/VenueDetail.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/vo/VenueDetailImage.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/vo/VenueDetailLink.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/vo/VenueDetailVenueHour.java
Labels: refactor, BE

#314 공연 스케줄 자동화 - 이벤트가 있는 주에 따른 로직 추가
  be/src/main/java/kr/codesquad/jazzmeet/global/util/CustomLocalDate.java
  be/src/main/java/kr/codesquad/jazzmeet/global/util/TextParser.java
  be/src/main/java/kr/codesquad/jazzmeet/show/repository/OcrHandler.java
  be/src/main/java/kr/codesquad/jazzmeet/show/repository/WebCrawler.java
Labels: feat, refactor, BE

#326 Fix/be/#325 cors httponly 추가
  be/src/main/java/kr/codesquad/jazzmeet/global/config/WebConfig.java
Labels: fix, BE

#330 fix: http 접근 가능하게 변경
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
  be/src/main/java/kr/codesquad/jazzmeet/global/config/WebConfig.java
Labels: fix, BE

#331 http 허용 배포
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
  be/src/main/java/kr/codesquad/jazzmeet/global/config/WebConfig.java
Labels: BE, release

#332 fix: 쿠키에 sameSite 설정 추가
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
Labels: fix, BE

#333 sameSite 설정 추가 배포
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
Labels: BE, release

#334 fix: 쿠키에 저장 도메인 확인을 위해 httpOnly false 변경
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
Labels: fix, BE

#335 쿠키 저장 도메인 확인용 배포
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
Labels: BE, release

#336 fix: 쿠키에 도메인 직접 설정
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
Labels: fix, BE

#337 쿠키에 도메인 직접 설정 배포
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
Labels: BE, release

#338 fix: 쿠키에 도메인 직접 설정 - 이름 변경
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
Labels: fix, BE

#339 쿠키 도메인명 변경 배포
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
Labels: BE, release

#340 fix: 쿠키에 도메인 직접 설정 - 이름 변경
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
Labels: fix, BE

#341 쿠키 도메인에서 https 문자 삭제 배포
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
Labels: BE, release

#342 fix: secure true 설정
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
Labels: fix, BE

#343 secure true 설정 배포
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
Labels: BE, release

#344 fix: 쿠키 도메인 삭제
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
Labels: fix, BE

#345 도메인 지정 삭제한 건 배포
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
Labels: BE, release
