Repository jazz-meet/jazz-meet, pull requests merged in 2024-03, with the labels that each got.

#346 fix: 서브도메인으로 변경
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
  be/src/main/java/kr/codesquad/jazzmeet/global/config/WebConfig.java
Labels: fix, BE

#347 서브도메인 변경 건 배포
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
  be/src/main/java/kr/codesquad/jazzmeet/global/config/WebConfig.java
Labels: BE, release

#324 공연장 - 관리자 API 권한 인증 추가
  be/src/main/java/kr/codesquad/jazzmeet/image/controller/ImageController.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/VenueController.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/Venue.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/mapper/VenueMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueFacade.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/service/VenueFacadeTest.java
Labels: refactor, BE

#327 공연 - 관리자 권한 추가
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
  be/src/main/java/kr/codesquad/jazzmeet/admin/mapper/AdminMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/admin/service/AdminService.java
  be/src/main/java/kr/codesquad/jazzmeet/show/controller/ShowController.java
Labels: fix, BE

#348 nginx 프록시 쿠키 경로 설정
  nginx/nginx.conf
Labels: fix, BE

#349 nignx 프록시 쿠키 경로 설정 추가, 관리자 API 권한 추가 배포
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
  be/src/main/java/kr/codesquad/jazzmeet/admin/mapper/AdminMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/admin/service/AdminService.java
  be/src/main/java/kr/codesquad/jazzmeet/image/controller/ImageController.java
  be/src/main/java/kr/codesquad/jazzmeet/show/controller/ShowController.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/controller/VenueController.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/entity/Venue.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/mapper/VenueMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/venue/service/VenueFacade.java
  be/src/test/java/kr/codesquad/jazzmeet/venue/service/VenueFacadeTest.java
  nginx/nginx.conf
Labels: BE, release

#351 nginx 프록시 쿠키 경로 삭제 배포
  nginx/nginx.conf
Labels: BE, release

#352 fix: 서브 도메인 사용 시 sameSite lax 사용하도록 변경
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
Labels: fix, BE

#353 서브 도메인 사용 시 sameSite lax 사용하도록 변경 배포
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
Labels: BE, release

#354 exposedHeaders 추가
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
  be/src/main/java/kr/codesquad/jazzmeet/global/config/WebConfig.java
Labels: fix, BE

#356 fix: same site lax, httpOnly true 설정
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
Labels: fix, BE

#357 same site lax, httpOnly true 설정 배포
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
Labels: BE, release

#358 문의 어드민 로그인 인증 기능
  be/src/main/java/kr/codesquad/jazzmeet/global/error/statuscode/InquiryErrorCode.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/controller/InquiryController.java
  be/src/main/java/kr/codesquad/jazzmeet/inquiry/service/InquiryService.java
  be/src/test/java/kr/codesquad/jazzmeet/fixture/InquiryFixture.java
  be/src/test/java/kr/codesquad/jazzmeet/inquiry/service/InquiryServiceTest.java
Labels: fix, feat, BE

#361 블랙리스트 삭제
  be/src/main/java/kr/codesquad/jazzmeet/admin/controller/AdminController.java
  be/src/main/java/kr/codesquad/jazzmeet/admin/service/AdminService.java
  be/src/main/java/kr/codesquad/jazzmeet/global/jwt/JwtProvider.java
  be/src/main/java/kr/codesquad/jazzmeet/global/permission/PermissionInterceptor.java
  be/src/main/java/kr/codesquad/jazzmeet/global/util/RedisUtil.java
Labels: fix, BE

#364 공연 등록 시 Admin 추가
  be/src/main/java/kr/codesquad/jazzmeet/admin/service/AdminService.java
  be/src/main/java/kr/codesquad/jazzmeet/show/controller/ShowController.java
  be/src/main/java/kr/codesquad/jazzmeet/show/entity/Show.java
  be/src/main/java/kr/codesquad/jazzmeet/show/mapper/ShowMapper.java
  be/src/main/java/kr/codesquad/jazzmeet/show/service/ShowScheduler.java
  be/src/main/java/kr/codesquad/jazzmeet/show/service/ShowService.java
  be/src/test/java/kr/codesquad/jazzmeet/admin/service/AdminServiceTest.java
  be/src/test/java/kr/codesquad/jazzmeet/show/controller/ShowControllerTest.java
  be/src/test/java/kr/codesquad/jazzmeet/show/service/ShowServiceTest.java
Labels: fix, BE

#367 Be/fix/#366 공연 자동화 entry55 크롤링 스크립트 수정
  be/src/main/java/kr/codesquad/jazzmeet/global/error/statuscode/ShowErrorCode.java
  be/src/main/java/kr/codesquad/jazzmeet/global/util/CustomLocalDate.java
  be/src/main/java/kr/codesquad/jazzmeet/global/util/TextParser.java
  be/src/main/java/kr/codesquad/jazzmeet/image/service/ImageService.java
  be/src/main/java/kr/codesquad/jazzmeet/show/repository/OcrHandler.java
  be/src/main/java/kr/codesquad/jazzmeet/show/repository/WebCrawler.java
  be/src/main/java/kr/codesquad/jazzmeet/show/util/ResponseParser.java
  be/src/main/java/kr/codesquad/jazzmeet/show/util/TextParser.java
Labels: fix, refactor, BE
